# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_run_event import AgentRunEvent
    from .agent_run_request import AgentRunRequest
    from .agent_run_response import AgentRunResponse
    from .agent_run_usage import AgentRunUsage
    from .agent_tool_call import AgentToolCall
    from .annotation_schema import AnnotationSchema
    from .batch_write_options import BatchWriteOptions
    from .batch_write_options_mode import BatchWriteOptionsMode
    from .batch_write_response import BatchWriteResponse
    from .error_schema import ErrorSchema
    from .file_content_schema import FileContentSchema
    from .file_info_schema import FileInfoSchema
    from .file_upload_schema import FileUploadSchema
    from .file_upload_url_schema import FileUploadUrlSchema
    from .job_trigger_category import JobTriggerCategory
    from .job_trigger_schema import JobTriggerSchema
    from .ml_model_task_type import MlModelTaskType
    from .ml_problem_type import MlProblemType
    from .off_platform_job_execution_schema import OffPlatformJobExecutionSchema
    from .parameter_definition_schema import ParameterDefinitionSchema
    from .parameter_definition_schema_widget_type import ParameterDefinitionSchemaWidgetType
    from .predict_response_schema import PredictResponseSchema
    from .predicted_annotation_schema import PredictedAnnotationSchema
    from .quality_preset import QualityPreset
    from .query_result import QueryResult
    from .queryable_column_schema import QueryableColumnSchema
    from .queryable_table_schema import QueryableTableSchema
    from .revert_result_schema import RevertResultSchema
    from .save_annotation_schema import SaveAnnotationSchema
    from .script_edit_schema import ScriptEditSchema
    from .sent_notification_schema import SentNotificationSchema
    from .sent_notification_schema_status import SentNotificationSchemaStatus
    from .series_write import SeriesWrite
    from .series_write_parent import SeriesWriteParent
    from .series_write_result import SeriesWriteResult
    from .start_job_execution_schema import StartJobExecutionSchema
    from .table_summary import TableSummary
    from .table_write import TableWrite
    from .table_write_mode import TableWriteMode
    from .table_write_on_match import TableWriteOnMatch
    from .table_write_result import TableWriteResult
    from .tools_job_schema import ToolsJobSchema
    from .tools_ml_model_detail_schema import ToolsMlModelDetailSchema
    from .validation_error_schema import ValidationErrorSchema
    from .write_data_error_response import WriteDataErrorResponse
    from .write_data_problem import WriteDataProblem
    from .write_data_response import WriteDataResponse
    from .write_plan import WritePlan
_dynamic_imports: typing.Dict[str, str] = {
    "AgentRunEvent": ".agent_run_event",
    "AgentRunRequest": ".agent_run_request",
    "AgentRunResponse": ".agent_run_response",
    "AgentRunUsage": ".agent_run_usage",
    "AgentToolCall": ".agent_tool_call",
    "AnnotationSchema": ".annotation_schema",
    "BatchWriteOptions": ".batch_write_options",
    "BatchWriteOptionsMode": ".batch_write_options_mode",
    "BatchWriteResponse": ".batch_write_response",
    "ErrorSchema": ".error_schema",
    "FileContentSchema": ".file_content_schema",
    "FileInfoSchema": ".file_info_schema",
    "FileUploadSchema": ".file_upload_schema",
    "FileUploadUrlSchema": ".file_upload_url_schema",
    "JobTriggerCategory": ".job_trigger_category",
    "JobTriggerSchema": ".job_trigger_schema",
    "MlModelTaskType": ".ml_model_task_type",
    "MlProblemType": ".ml_problem_type",
    "OffPlatformJobExecutionSchema": ".off_platform_job_execution_schema",
    "ParameterDefinitionSchema": ".parameter_definition_schema",
    "ParameterDefinitionSchemaWidgetType": ".parameter_definition_schema_widget_type",
    "PredictResponseSchema": ".predict_response_schema",
    "PredictedAnnotationSchema": ".predicted_annotation_schema",
    "QualityPreset": ".quality_preset",
    "QueryResult": ".query_result",
    "QueryableColumnSchema": ".queryable_column_schema",
    "QueryableTableSchema": ".queryable_table_schema",
    "RevertResultSchema": ".revert_result_schema",
    "SaveAnnotationSchema": ".save_annotation_schema",
    "ScriptEditSchema": ".script_edit_schema",
    "SentNotificationSchema": ".sent_notification_schema",
    "SentNotificationSchemaStatus": ".sent_notification_schema_status",
    "SeriesWrite": ".series_write",
    "SeriesWriteParent": ".series_write_parent",
    "SeriesWriteResult": ".series_write_result",
    "StartJobExecutionSchema": ".start_job_execution_schema",
    "TableSummary": ".table_summary",
    "TableWrite": ".table_write",
    "TableWriteMode": ".table_write_mode",
    "TableWriteOnMatch": ".table_write_on_match",
    "TableWriteResult": ".table_write_result",
    "ToolsJobSchema": ".tools_job_schema",
    "ToolsMlModelDetailSchema": ".tools_ml_model_detail_schema",
    "ValidationErrorSchema": ".validation_error_schema",
    "WriteDataErrorResponse": ".write_data_error_response",
    "WriteDataProblem": ".write_data_problem",
    "WriteDataResponse": ".write_data_response",
    "WritePlan": ".write_plan",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentRunEvent",
    "AgentRunRequest",
    "AgentRunResponse",
    "AgentRunUsage",
    "AgentToolCall",
    "AnnotationSchema",
    "BatchWriteOptions",
    "BatchWriteOptionsMode",
    "BatchWriteResponse",
    "ErrorSchema",
    "FileContentSchema",
    "FileInfoSchema",
    "FileUploadSchema",
    "FileUploadUrlSchema",
    "JobTriggerCategory",
    "JobTriggerSchema",
    "MlModelTaskType",
    "MlProblemType",
    "OffPlatformJobExecutionSchema",
    "ParameterDefinitionSchema",
    "ParameterDefinitionSchemaWidgetType",
    "PredictResponseSchema",
    "PredictedAnnotationSchema",
    "QualityPreset",
    "QueryResult",
    "QueryableColumnSchema",
    "QueryableTableSchema",
    "RevertResultSchema",
    "SaveAnnotationSchema",
    "ScriptEditSchema",
    "SentNotificationSchema",
    "SentNotificationSchemaStatus",
    "SeriesWrite",
    "SeriesWriteParent",
    "SeriesWriteResult",
    "StartJobExecutionSchema",
    "TableSummary",
    "TableWrite",
    "TableWriteMode",
    "TableWriteOnMatch",
    "TableWriteResult",
    "ToolsJobSchema",
    "ToolsMlModelDetailSchema",
    "ValidationErrorSchema",
    "WriteDataErrorResponse",
    "WriteDataProblem",
    "WriteDataResponse",
    "WritePlan",
]
