# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PredictedAnnotationSchema(UniversalBaseModel):
    """
    A predicted mask shaped as an annotation payload, tied back to the
    input row's image file. Nothing is persisted by predict: to store it,
    pass it to POST /v1/images/{file_id}/annotations (the images annotate
    tool), with is_human_vetted=true when a human reviewed the prediction
    and omitted (false) for automated saves.
    """

    file_id: str
    label: str
    mask: str
    width: int
    height: int
    foreground_fraction: float
    confidence: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
