# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ScriptEditSchema(UniversalBaseModel):
    """
    One exact text replacement in a job's script.
    """

    old_string: str = pydantic.Field()
    """
    Text to replace. Must match the script exactly once, including whitespace and indentation; include surrounding lines to make it unique.
    """

    new_string: str = pydantic.Field()
    """
    Replacement text. An empty string deletes the match.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
