# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.series_write import SeriesWrite
from ..types.table_write import TableWrite
from ..types.write_data_response import WriteDataResponse
from .raw_client import AsyncRawDataClient, RawDataClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDataClient
        """
        return self._raw_client

    def write(
        self,
        *,
        tables: typing.Optional[typing.Sequence[TableWrite]] = OMIT,
        series: typing.Optional[typing.Sequence[SeriesWrite]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        return_rows: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WriteDataResponse:
        """
        Insert, upsert, update, or delete rows across tables, and write raw
        series, in a single transaction.

        Table writes target the organization's tables from get_schema or core
        tables such as experiment, operation, and carrier. They are applied in
        request order, so one request can create a sample and then the
        measurements that reference it: label a row with "_ref": "s1" and point at
        it with "@s1" from a foreign key column of any later row. A foreign key may
        also be a lookup object such as {"name": "S-001"} that matches exactly one
        row that existed before the request. Primary keys are generated when
        omitted where the table allows it, and are always returned in input
        order.

        A series holds the points of one parent row in a raw table as one list per
        column. Writing a series replaces the parent's existing series in that
        table, so repeating a write is safe. The server fills in the primary key,
        the parent foreign key, and an integer order column.

        Every row, series, and lookup is checked before anything is written, and
        all of those problems are reported together in errors. Each has a path
        naming its place in the request, such as tables[1].rows[0].sample. Keys
        for upsert, update, and delete are matched as each table write is
        applied, and any failure rolls back the whole request. The write is recorded under a job execution,
        created if none is given. Reverting that execution deletes the rows it
        created along with their series; updates, deletes, and series written to
        existing parents are not undone.

        The request body must be under 4.5 MB, which the row and series value
        limits keep most requests within.

        A write that waits too long on rows other writes are changing fails with
        429 and changes nothing. Retry it after the Retry-After header's delay.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Optional[typing.Sequence[TableWrite]]
            Table writes, applied in order. A row may reference only rows that appear before it. At most 10,000 rows across all table writes.

        series : typing.Optional[typing.Sequence[SeriesWrite]]
            Raw series, applied after the table writes. Writing a series replaces any series the parent already has in that table. At most 250,000 values across all columns of all series.

        job_execution_id : typing.Optional[str]
            Job execution to record this write under. When omitted, one is created and returned so the write can be reverted as a unit.

        job_name : typing.Optional[str]
            Name of the job an auto-created execution belongs to. Defaults to 'Off-Platform Manual Job'.

        dry_run : typing.Optional[bool]
            Run every validation and constraint check, then roll back instead of committing.

        return_rows : typing.Optional[bool]
            Include the written rows of each table write in its result.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WriteDataResponse
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.data.write()
        """
        _response = self._raw_client.write(
            tables=tables,
            series=series,
            job_execution_id=job_execution_id,
            job_name=job_name,
            dry_run=dry_run,
            return_rows=return_rows,
            request_options=request_options,
        )
        return _response.data


class AsyncDataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDataClient
        """
        return self._raw_client

    async def write(
        self,
        *,
        tables: typing.Optional[typing.Sequence[TableWrite]] = OMIT,
        series: typing.Optional[typing.Sequence[SeriesWrite]] = OMIT,
        job_execution_id: typing.Optional[str] = OMIT,
        job_name: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        return_rows: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WriteDataResponse:
        """
        Insert, upsert, update, or delete rows across tables, and write raw
        series, in a single transaction.

        Table writes target the organization's tables from get_schema or core
        tables such as experiment, operation, and carrier. They are applied in
        request order, so one request can create a sample and then the
        measurements that reference it: label a row with "_ref": "s1" and point at
        it with "@s1" from a foreign key column of any later row. A foreign key may
        also be a lookup object such as {"name": "S-001"} that matches exactly one
        row that existed before the request. Primary keys are generated when
        omitted where the table allows it, and are always returned in input
        order.

        A series holds the points of one parent row in a raw table as one list per
        column. Writing a series replaces the parent's existing series in that
        table, so repeating a write is safe. The server fills in the primary key,
        the parent foreign key, and an integer order column.

        Every row, series, and lookup is checked before anything is written, and
        all of those problems are reported together in errors. Each has a path
        naming its place in the request, such as tables[1].rows[0].sample. Keys
        for upsert, update, and delete are matched as each table write is
        applied, and any failure rolls back the whole request. The write is recorded under a job execution,
        created if none is given. Reverting that execution deletes the rows it
        created along with their series; updates, deletes, and series written to
        existing parents are not undone.

        The request body must be under 4.5 MB, which the row and series value
        limits keep most requests within.

        A write that waits too long on rows other writes are changing fails with
        429 and changes nothing. Retry it after the Retry-After header's delay.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        tables : typing.Optional[typing.Sequence[TableWrite]]
            Table writes, applied in order. A row may reference only rows that appear before it. At most 10,000 rows across all table writes.

        series : typing.Optional[typing.Sequence[SeriesWrite]]
            Raw series, applied after the table writes. Writing a series replaces any series the parent already has in that table. At most 250,000 values across all columns of all series.

        job_execution_id : typing.Optional[str]
            Job execution to record this write under. When omitted, one is created and returned so the write can be reverted as a unit.

        job_name : typing.Optional[str]
            Name of the job an auto-created execution belongs to. Defaults to 'Off-Platform Manual Job'.

        dry_run : typing.Optional[bool]
            Run every validation and constraint check, then roll back instead of committing.

        return_rows : typing.Optional[bool]
            Include the written rows of each table write in its result.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WriteDataResponse
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.data.write()


        asyncio.run(main())
        """
        _response = await self._raw_client.write(
            tables=tables,
            series=series,
            job_execution_id=job_execution_id,
            job_name=job_name,
            dry_run=dry_run,
            return_rows=return_rows,
            request_options=request_options,
        )
        return _response.data
