# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.ml_model_task_type import MlModelTaskType
from ..types.ml_problem_type import MlProblemType
from ..types.predict_response_schema import PredictResponseSchema
from ..types.quality_preset import QualityPreset
from ..types.tools_ml_model_detail_schema import ToolsMlModelDetailSchema
from .raw_client import AsyncRawModelsClient, RawModelsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ModelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawModelsClient
        """
        return self._raw_client

    def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        min_region_pixels: typing.Optional[int] = OMIT,
        max_hole_pixels: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PredictResponseSchema:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values; list_ml_models shows the columns each model expects. Returns one
        prediction per input row, plus per-class probabilities for classifiers.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        min_region_pixels : typing.Optional[int]
            Segmentation models only. Drops predicted regions with fewer pixels than this. Pixels are counted on the hole-filled mask at the model's inference resolution.

        max_hole_pixels : typing.Optional[int]
            Segmentation models only. Fills enclosed holes of up to this many pixels in each predicted mask before it is split into regions. Null fills every hole; 0 keeps all holes, so ring-shaped predictions stay rings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PredictResponseSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.models.predict(
            data=[{"key": "value"}],
        )
        """
        _response = self._raw_client.predict(
            data=data,
            ml_model_id=ml_model_id,
            ml_model_name=ml_model_name,
            min_region_pixels=min_region_pixels,
            max_hole_pixels=max_hole_pixels,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsMlModelDetailSchema:
        """
        Get one ML model's training status and results.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.models.get(
            ml_model_id="ml_model_id",
        )
        """
        _response = self._raw_client.get(ml_model_id, request_options=request_options)
        return _response.data

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[ToolsMlModelDetailSchema]:
        """
        List the organization's ML models, newest first.

        Returns every non-archived model with its task type, target and feature
        columns, training status, and evaluation metrics. The status describes the
        newest version. A model serves predictions only while currently_active is
        true; a retrain stops it serving until the new version is ready.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsMlModelDetailSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.models.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def train(
        self,
        *,
        target_column: str,
        dataset_id: str,
        description: typing.Optional[str] = OMIT,
        task_type: typing.Optional[MlModelTaskType] = OMIT,
        quality_preset: typing.Optional[QualityPreset] = OMIT,
        feature_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        image_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        problem_type: typing.Optional[MlProblemType] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsMlModelDetailSchema:
        """
        Train a new ML model on a dataset, or retrain an existing one.

        To train a new model, pass name and omit ml_model_id. To retrain, pass
        ml_model_id and omit name; the model keeps its name and gains a new
        version. dataset_id and target_column are always required, and every
        column must exist in the dataset. Training runs in the background;
        check its progress with get_ml_model.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_column : str

        dataset_id : str

        description : typing.Optional[str]

        task_type : typing.Optional[MlModelTaskType]

        quality_preset : typing.Optional[QualityPreset]

        feature_columns : typing.Optional[typing.Sequence[str]]

        image_columns : typing.Optional[typing.Sequence[str]]

        problem_type : typing.Optional[MlProblemType]

        ml_model_id : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.models.train(
            target_column="target_column",
            dataset_id="dataset_id",
        )
        """
        _response = self._raw_client.train(
            target_column=target_column,
            dataset_id=dataset_id,
            description=description,
            task_type=task_type,
            quality_preset=quality_preset,
            feature_columns=feature_columns,
            image_columns=image_columns,
            problem_type=problem_type,
            ml_model_id=ml_model_id,
            name=name,
            request_options=request_options,
        )
        return _response.data

    def cancel_training(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsMlModelDetailSchema:
        """
        Cancel the model's in-flight training runs.

        Overlapping retrains can leave several versions pending or training at
        once, so the cancel is model-wide: every in-flight version is marked
        'cancelled' and its cloud training jobs are stopped. Fails when no
        training is pending or running.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.models.cancel_training(
            ml_model_id="ml_model_id",
        )
        """
        _response = self._raw_client.cancel_training(ml_model_id, request_options=request_options)
        return _response.data


class AsyncModelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawModelsClient
        """
        return self._raw_client

    async def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        min_region_pixels: typing.Optional[int] = OMIT,
        max_hole_pixels: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PredictResponseSchema:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values; list_ml_models shows the columns each model expects. Returns one
        prediction per input row, plus per-class probabilities for classifiers.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        min_region_pixels : typing.Optional[int]
            Segmentation models only. Drops predicted regions with fewer pixels than this. Pixels are counted on the hole-filled mask at the model's inference resolution.

        max_hole_pixels : typing.Optional[int]
            Segmentation models only. Fills enclosed holes of up to this many pixels in each predicted mask before it is split into regions. Null fills every hole; 0 keeps all holes, so ring-shaped predictions stay rings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PredictResponseSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.models.predict(
                data=[{"key": "value"}],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.predict(
            data=data,
            ml_model_id=ml_model_id,
            ml_model_name=ml_model_name,
            min_region_pixels=min_region_pixels,
            max_hole_pixels=max_hole_pixels,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsMlModelDetailSchema:
        """
        Get one ML model's training status and results.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.models.get(
                ml_model_id="ml_model_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(ml_model_id, request_options=request_options)
        return _response.data

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ToolsMlModelDetailSchema]:
        """
        List the organization's ML models, newest first.

        Returns every non-archived model with its task type, target and feature
        columns, training status, and evaluation metrics. The status describes the
        newest version. A model serves predictions only while currently_active is
        true; a retrain stops it serving until the new version is ready.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsMlModelDetailSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.models.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def train(
        self,
        *,
        target_column: str,
        dataset_id: str,
        description: typing.Optional[str] = OMIT,
        task_type: typing.Optional[MlModelTaskType] = OMIT,
        quality_preset: typing.Optional[QualityPreset] = OMIT,
        feature_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        image_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        problem_type: typing.Optional[MlProblemType] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsMlModelDetailSchema:
        """
        Train a new ML model on a dataset, or retrain an existing one.

        To train a new model, pass name and omit ml_model_id. To retrain, pass
        ml_model_id and omit name; the model keeps its name and gains a new
        version. dataset_id and target_column are always required, and every
        column must exist in the dataset. Training runs in the background;
        check its progress with get_ml_model.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_column : str

        dataset_id : str

        description : typing.Optional[str]

        task_type : typing.Optional[MlModelTaskType]

        quality_preset : typing.Optional[QualityPreset]

        feature_columns : typing.Optional[typing.Sequence[str]]

        image_columns : typing.Optional[typing.Sequence[str]]

        problem_type : typing.Optional[MlProblemType]

        ml_model_id : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.models.train(
                target_column="target_column",
                dataset_id="dataset_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.train(
            target_column=target_column,
            dataset_id=dataset_id,
            description=description,
            task_type=task_type,
            quality_preset=quality_preset,
            feature_columns=feature_columns,
            image_columns=image_columns,
            problem_type=problem_type,
            ml_model_id=ml_model_id,
            name=name,
            request_options=request_options,
        )
        return _response.data

    async def cancel_training(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolsMlModelDetailSchema:
        """
        Cancel the model's in-flight training runs.

        Overlapping retrains can leave several versions pending or training at
        once, so the cancel is model-wide: every in-flight version is marked
        'cancelled' and its cloud training jobs are stopped. Fails when no
        training is pending or running.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsMlModelDetailSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.models.cancel_training(
                ml_model_id="ml_model_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_training(ml_model_id, request_options=request_options)
        return _response.data
