# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error_schema import ErrorSchema
from ..types.ml_model_task_type import MlModelTaskType
from ..types.ml_problem_type import MlProblemType
from ..types.predict_response_schema import PredictResponseSchema
from ..types.quality_preset import QualityPreset
from ..types.tools_ml_model_detail_schema import ToolsMlModelDetailSchema
from ..types.validation_error_schema import ValidationErrorSchema
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawModelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        pixel_threshold: typing.Optional[float] = OMIT,
        min_region_pixels: typing.Optional[int] = OMIT,
        max_hole_pixels: typing.Optional[int] = OMIT,
        min_confidence: typing.Optional[float] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PredictResponseSchema]:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values; list_ml_models shows the columns each model expects. Returns one
        prediction per input row, plus per-class probabilities for classifiers.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        pixel_threshold : typing.Optional[float]
            Segmentation models only. A pixel belongs to a predicted region when the model's probability for it exceeds this. Lower values find fainter regions and grow existing ones. Higher values keep only confident pixels. Probabilities are uncalibrated, so useful values depend on the model.

        min_region_pixels : typing.Optional[int]
            Segmentation models only. Drops predicted regions with fewer pixels than this. Pixels are counted on the hole-filled mask at the model's inference resolution.

        max_hole_pixels : typing.Optional[int]
            Segmentation models only. Fills enclosed holes of up to this many pixels in each predicted mask before it is split into regions. Null fills every hole. 0 keeps all holes, so ring-shaped predictions stay rings.

        min_confidence : typing.Optional[float]
            Segmentation models only. Drops predicted regions whose confidence, the mean probability of their pixels, is below this.

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PredictResponseSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/ml-models/predict",
            method="POST",
            json={
                "pixel_threshold": pixel_threshold,
                "min_region_pixels": min_region_pixels,
                "max_hole_pixels": max_hole_pixels,
                "min_confidence": min_confidence,
                "ml_model_id": ml_model_id,
                "ml_model_name": ml_model_name,
                "data": data,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PredictResponseSchema,
                    parse_obj_as(
                        type_=PredictResponseSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ToolsMlModelDetailSchema]:
        """
        Get one ML model's training status and results.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/ml-models/{encode_path_param(ml_model_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[ToolsMlModelDetailSchema]]:
        """
        List the organization's ML models, newest first.

        Returns every non-archived model with its task type, target and feature
        columns, training status, and evaluation metrics. The status describes the
        newest version. A model serves predictions only while currently_active is
        true; a retrain stops it serving until the new version is ready.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[ToolsMlModelDetailSchema]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/ml-models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ToolsMlModelDetailSchema],
                    parse_obj_as(
                        type_=typing.List[ToolsMlModelDetailSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def train(
        self,
        *,
        target_column: str,
        dataset_id: str,
        description: typing.Optional[str] = OMIT,
        task_type: typing.Optional[MlModelTaskType] = OMIT,
        quality_preset: typing.Optional[QualityPreset] = OMIT,
        feature_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        image_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        problem_type: typing.Optional[MlProblemType] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ToolsMlModelDetailSchema]:
        """
        Train a new ML model on a dataset, or retrain an existing one.

        To train a new model, pass name and omit ml_model_id. To retrain, pass
        ml_model_id and omit name; the model keeps its name and gains a new
        version. dataset_id and target_column are always required, and every
        column must exist in the dataset. Training runs in the background;
        check its progress with get_ml_model.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_column : str

        dataset_id : str

        description : typing.Optional[str]

        task_type : typing.Optional[MlModelTaskType]

        quality_preset : typing.Optional[QualityPreset]

        feature_columns : typing.Optional[typing.Sequence[str]]

        image_columns : typing.Optional[typing.Sequence[str]]

        problem_type : typing.Optional[MlProblemType]

        ml_model_id : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/ml-models",
            method="POST",
            json={
                "description": description,
                "task_type": task_type,
                "target_column": target_column,
                "quality_preset": quality_preset,
                "dataset_id": dataset_id,
                "feature_columns": feature_columns,
                "image_columns": image_columns,
                "problem_type": problem_type,
                "ml_model_id": ml_model_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_training(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ToolsMlModelDetailSchema]:
        """
        Cancel the model's in-flight training runs.

        Overlapping retrains can leave several versions pending or training at
        once, so the cancel is model-wide: every in-flight version is marked
        'cancelled' and its cloud training jobs are stopped. Fails when no
        training is pending or running.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/ml-models/{encode_path_param(ml_model_id)}/cancel-training",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawModelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def predict(
        self,
        *,
        data: typing.Sequence[typing.Dict[str, typing.Any]],
        pixel_threshold: typing.Optional[float] = OMIT,
        min_region_pixels: typing.Optional[int] = OMIT,
        max_hole_pixels: typing.Optional[int] = OMIT,
        min_confidence: typing.Optional[float] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        ml_model_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PredictResponseSchema]:
        """
        Run predictions with a trained ML model.

        Identify the model by ml_model_id, or by ml_model_name (the name of a
        non-archived model). Each row in data maps the model's feature columns to
        values; list_ml_models shows the columns each model expects. Returns one
        prediction per input row, plus per-class probabilities for classifiers.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        data : typing.Sequence[typing.Dict[str, typing.Any]]

        pixel_threshold : typing.Optional[float]
            Segmentation models only. A pixel belongs to a predicted region when the model's probability for it exceeds this. Lower values find fainter regions and grow existing ones. Higher values keep only confident pixels. Probabilities are uncalibrated, so useful values depend on the model.

        min_region_pixels : typing.Optional[int]
            Segmentation models only. Drops predicted regions with fewer pixels than this. Pixels are counted on the hole-filled mask at the model's inference resolution.

        max_hole_pixels : typing.Optional[int]
            Segmentation models only. Fills enclosed holes of up to this many pixels in each predicted mask before it is split into regions. Null fills every hole. 0 keeps all holes, so ring-shaped predictions stay rings.

        min_confidence : typing.Optional[float]
            Segmentation models only. Drops predicted regions whose confidence, the mean probability of their pixels, is below this.

        ml_model_id : typing.Optional[str]

        ml_model_name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PredictResponseSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/ml-models/predict",
            method="POST",
            json={
                "pixel_threshold": pixel_threshold,
                "min_region_pixels": min_region_pixels,
                "max_hole_pixels": max_hole_pixels,
                "min_confidence": min_confidence,
                "ml_model_id": ml_model_id,
                "ml_model_name": ml_model_name,
                "data": data,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PredictResponseSchema,
                    parse_obj_as(
                        type_=PredictResponseSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ToolsMlModelDetailSchema]:
        """
        Get one ML model's training status and results.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/ml-models/{encode_path_param(ml_model_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[ToolsMlModelDetailSchema]]:
        """
        List the organization's ML models, newest first.

        Returns every non-archived model with its task type, target and feature
        columns, training status, and evaluation metrics. The status describes the
        newest version. A model serves predictions only while currently_active is
        true; a retrain stops it serving until the new version is ready.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[ToolsMlModelDetailSchema]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/ml-models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ToolsMlModelDetailSchema],
                    parse_obj_as(
                        type_=typing.List[ToolsMlModelDetailSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def train(
        self,
        *,
        target_column: str,
        dataset_id: str,
        description: typing.Optional[str] = OMIT,
        task_type: typing.Optional[MlModelTaskType] = OMIT,
        quality_preset: typing.Optional[QualityPreset] = OMIT,
        feature_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        image_columns: typing.Optional[typing.Sequence[str]] = OMIT,
        problem_type: typing.Optional[MlProblemType] = OMIT,
        ml_model_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ToolsMlModelDetailSchema]:
        """
        Train a new ML model on a dataset, or retrain an existing one.

        To train a new model, pass name and omit ml_model_id. To retrain, pass
        ml_model_id and omit name; the model keeps its name and gains a new
        version. dataset_id and target_column are always required, and every
        column must exist in the dataset. Training runs in the background;
        check its progress with get_ml_model.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        target_column : str

        dataset_id : str

        description : typing.Optional[str]

        task_type : typing.Optional[MlModelTaskType]

        quality_preset : typing.Optional[QualityPreset]

        feature_columns : typing.Optional[typing.Sequence[str]]

        image_columns : typing.Optional[typing.Sequence[str]]

        problem_type : typing.Optional[MlProblemType]

        ml_model_id : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/ml-models",
            method="POST",
            json={
                "description": description,
                "task_type": task_type,
                "target_column": target_column,
                "quality_preset": quality_preset,
                "dataset_id": dataset_id,
                "feature_columns": feature_columns,
                "image_columns": image_columns,
                "problem_type": problem_type,
                "ml_model_id": ml_model_id,
                "name": name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_training(
        self, ml_model_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ToolsMlModelDetailSchema]:
        """
        Cancel the model's in-flight training runs.

        Overlapping retrains can leave several versions pending or training at
        once, so the cancel is model-wide: every in-flight version is marked
        'cancelled' and its cloud training jobs are stopped. Fails when no
        training is pending or running.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        ml_model_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ToolsMlModelDetailSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/ml-models/{encode_path_param(ml_model_id)}/cancel-training",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ToolsMlModelDetailSchema,
                    parse_obj_as(
                        type_=ToolsMlModelDetailSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorSchema,
                        parse_obj_as(
                            type_=ValidationErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorSchema,
                        parse_obj_as(
                            type_=ErrorSchema,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
