# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.job_trigger_category import JobTriggerCategory
from ..types.off_platform_job_execution_schema import OffPlatformJobExecutionSchema
from ..types.parameter_definition_schema import ParameterDefinitionSchema
from ..types.revert_result_schema import RevertResultSchema
from ..types.script_edit_schema import ScriptEditSchema
from ..types.start_job_execution_schema import StartJobExecutionSchema
from ..types.tools_job_schema import ToolsJobSchema
from .raw_client import AsyncRawJobsClient, RawJobsClient
from .types.update_job_execution_status_schema_status import UpdateJobExecutionStatusSchemaStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        name: typing.Optional[str] = None,
        archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ToolsJobSchema]:
        """
        List the organization's jobs, newest first.

        Pass name to look up one job, since job names are unique within an
        organization; the list is then empty or holds that job. Archived jobs
        are left out unless archived is true.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        name : typing.Optional[str]

        archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsJobSchema]
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.list()
        """
        _response = self._raw_client.list(name=name, archived=archived, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        code: str,
        description: typing.Optional[str] = OMIT,
        trigger_enabled: typing.Optional[bool] = OMIT,
        trigger_category: typing.Optional[JobTriggerCategory] = OMIT,
        trigger_instrument_id: typing.Optional[str] = OMIT,
        trigger_conditions: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parameter_definitions: typing.Optional[typing.Sequence[ParameterDefinitionSchema]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobSchema:
        """
        Create a job that runs a Python script on the platform.

        The code becomes the job's script; declare its dependencies inline in a
        PEP 723 `# /// script` block. The job then appears on the platform, where
        it can be run and its executions reviewed. To change an existing job's
        name, description, or code, use update_job instead.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        name : str
            Name of the job. Unique within the organization.

        code : str
            Python source of the script the job runs. Declare dependencies inline in a PEP 723 `# /// script` block.

        description : typing.Optional[str]
            What the job does.

        trigger_enabled : typing.Optional[bool]
            True runs the job automatically when its trigger fires.

        trigger_category : typing.Optional[JobTriggerCategory]
            What runs the job automatically: file_uploaded runs it on each uploaded file that matches the conditions; job_completed runs it on the output files of another job's executions; schedule configures a recurring cron schedule. Required when trigger_enabled is true.

        trigger_instrument_id : typing.Optional[str]
            Restricts a file_uploaded trigger to files from this instrument.

        trigger_conditions : typing.Optional[typing.Dict[str, typing.Any]]
            Filters on the triggering event. For file_uploaded, any of file_name_pattern, file_extensions (list of strings starting with '.'; files with no extension always pass), source_type, min_size_kb, and max_size_kb (both inclusive). file_name_pattern is a case-sensitive glob in which * matches any characters, including folder separators, ? matches one character, and '/' and '\\' each match either separator. It must match the file's whole path or the part after any separator, so '*.csv' and 'run_*.csv' match files in any folder. For job_completed, source_job_id (required) and statuses (list drawn from completed and failed; defaults to completed). For schedule, cron (required five-field expression: minute, hour, day of month, month, day of week) and timezone (required IANA timezone, e.g. America/Los_Angeles). Cron supports numbers, month and weekday names, *, ranges, lists, and steps.

        parameter_definitions : typing.Optional[typing.Sequence[ParameterDefinitionSchema]]
            Inputs the script reads at run time. Each is rendered as a form control when the job is run on the platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.create(
            name="name",
            code="code",
        )
        """
        _response = self._raw_client.create(
            name=name,
            code=code,
            description=description,
            trigger_enabled=trigger_enabled,
            trigger_category=trigger_category,
            trigger_instrument_id=trigger_instrument_id,
            trigger_conditions=trigger_conditions,
            parameter_definitions=parameter_definitions,
            request_options=request_options,
        )
        return _response.data

    def update(
        self,
        job_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        code: typing.Optional[str] = OMIT,
        edits: typing.Optional[typing.Sequence[ScriptEditSchema]] = OMIT,
        archived: typing.Optional[bool] = OMIT,
        trigger_enabled: typing.Optional[bool] = OMIT,
        trigger_category: typing.Optional[JobTriggerCategory] = OMIT,
        trigger_instrument_id: typing.Optional[str] = OMIT,
        trigger_conditions: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parameter_definitions: typing.Optional[typing.Sequence[ParameterDefinitionSchema]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobSchema:
        """
        Change a job's name, description, code, trigger, or parameters, or
        archive it.

        Only the fields passed are changed. To change part of the script, pass
        edits: exact replacements of text in the current script. Pass code only to
        replace the whole script. New code is stored as a new version of the job's
        script, so earlier executions keep the version they ran. To create a job,
        use create_job instead.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        job_id : str

        name : typing.Optional[str]
            New name for the job.

        description : typing.Optional[str]
            New description for the job. Pass an empty string to clear it.

        code : typing.Optional[str]
            Complete new Python source for the job's script, stored as a new script version. Declare dependencies inline in a PEP 723 `# /// script` block. For a change to part of the script, pass edits instead.

        edits : typing.Optional[typing.Sequence[ScriptEditSchema]]
            Replacements applied in order to the job's current script, stored as a new script version. Each old_string is matched against the script as left by the edits before it. If any edit fails to match, no change is saved. Cannot be combined with code.

        archived : typing.Optional[bool]
            True archives the job, hiding it from the active job list; false restores it.

        trigger_enabled : typing.Optional[bool]
            True creates or replaces the job's trigger from the trigger fields; false removes it.

        trigger_category : typing.Optional[JobTriggerCategory]
            What runs the job automatically: file_uploaded runs it on each uploaded file that matches the conditions; job_completed runs it on the output files of another job's executions; schedule configures a recurring cron schedule. Required when trigger_enabled is true.

        trigger_instrument_id : typing.Optional[str]
            Restricts a file_uploaded trigger to files from this instrument.

        trigger_conditions : typing.Optional[typing.Dict[str, typing.Any]]
            Filters on the triggering event. For file_uploaded, any of file_name_pattern, file_extensions (list of strings starting with '.'; files with no extension always pass), source_type, min_size_kb, and max_size_kb (both inclusive). file_name_pattern is a case-sensitive glob in which * matches any characters, including folder separators, ? matches one character, and '/' and '\\' each match either separator. It must match the file's whole path or the part after any separator, so '*.csv' and 'run_*.csv' match files in any folder. For job_completed, source_job_id (required) and statuses (list drawn from completed and failed; defaults to completed). For schedule, cron (required five-field expression: minute, hour, day of month, month, day of week) and timezone (required IANA timezone, e.g. America/Los_Angeles). Cron supports numbers, month and weekday names, *, ranges, lists, and steps.

        parameter_definitions : typing.Optional[typing.Sequence[ParameterDefinitionSchema]]
            Inputs the script reads at run time. Each is rendered as a form control when the job is run on the platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.update(
            job_id="job_id",
        )
        """
        _response = self._raw_client.update(
            job_id,
            name=name,
            description=description,
            code=code,
            edits=edits,
            archived=archived,
            trigger_enabled=trigger_enabled,
            trigger_category=trigger_category,
            trigger_instrument_id=trigger_instrument_id,
            trigger_conditions=trigger_conditions,
            parameter_definitions=parameter_definitions,
            request_options=request_options,
        )
        return _response.data

    def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric, StartJobExecutionSchema

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.start(
            request=StartJobExecutionSchema(),
        )
        """
        _response = self._raw_client.start(request=request, request_options=request_options)
        return _response.data

    def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.close(
            execution_id="execution_id",
            status="completed",
        )
        """
        _response = self._raw_client.close(execution_id, status=status, request_options=request_options)
        return _response.data

    def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        from labric import Labric

        client = Labric(
            api_key="YOUR_API_KEY",
        )
        client.jobs.revert(
            execution_id="execution_id",
        )
        """
        _response = self._raw_client.revert(execution_id, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        name: typing.Optional[str] = None,
        archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ToolsJobSchema]:
        """
        List the organization's jobs, newest first.

        Pass name to look up one job, since job names are unique within an
        organization; the list is then empty or holds that job. Archived jobs
        are left out unless archived is true.

        Requires an API key with the `read` scope.

        Parameters
        ----------
        name : typing.Optional[str]

        archived : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ToolsJobSchema]
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(name=name, archived=archived, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        code: str,
        description: typing.Optional[str] = OMIT,
        trigger_enabled: typing.Optional[bool] = OMIT,
        trigger_category: typing.Optional[JobTriggerCategory] = OMIT,
        trigger_instrument_id: typing.Optional[str] = OMIT,
        trigger_conditions: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parameter_definitions: typing.Optional[typing.Sequence[ParameterDefinitionSchema]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobSchema:
        """
        Create a job that runs a Python script on the platform.

        The code becomes the job's script; declare its dependencies inline in a
        PEP 723 `# /// script` block. The job then appears on the platform, where
        it can be run and its executions reviewed. To change an existing job's
        name, description, or code, use update_job instead.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        name : str
            Name of the job. Unique within the organization.

        code : str
            Python source of the script the job runs. Declare dependencies inline in a PEP 723 `# /// script` block.

        description : typing.Optional[str]
            What the job does.

        trigger_enabled : typing.Optional[bool]
            True runs the job automatically when its trigger fires.

        trigger_category : typing.Optional[JobTriggerCategory]
            What runs the job automatically: file_uploaded runs it on each uploaded file that matches the conditions; job_completed runs it on the output files of another job's executions; schedule configures a recurring cron schedule. Required when trigger_enabled is true.

        trigger_instrument_id : typing.Optional[str]
            Restricts a file_uploaded trigger to files from this instrument.

        trigger_conditions : typing.Optional[typing.Dict[str, typing.Any]]
            Filters on the triggering event. For file_uploaded, any of file_name_pattern, file_extensions (list of strings starting with '.'; files with no extension always pass), source_type, min_size_kb, and max_size_kb (both inclusive). file_name_pattern is a case-sensitive glob in which * matches any characters, including folder separators, ? matches one character, and '/' and '\\' each match either separator. It must match the file's whole path or the part after any separator, so '*.csv' and 'run_*.csv' match files in any folder. For job_completed, source_job_id (required) and statuses (list drawn from completed and failed; defaults to completed). For schedule, cron (required five-field expression: minute, hour, day of month, month, day of week) and timezone (required IANA timezone, e.g. America/Los_Angeles). Cron supports numbers, month and weekday names, *, ranges, lists, and steps.

        parameter_definitions : typing.Optional[typing.Sequence[ParameterDefinitionSchema]]
            Inputs the script reads at run time. Each is rendered as a form control when the job is run on the platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.create(
                name="name",
                code="code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            code=code,
            description=description,
            trigger_enabled=trigger_enabled,
            trigger_category=trigger_category,
            trigger_instrument_id=trigger_instrument_id,
            trigger_conditions=trigger_conditions,
            parameter_definitions=parameter_definitions,
            request_options=request_options,
        )
        return _response.data

    async def update(
        self,
        job_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        code: typing.Optional[str] = OMIT,
        edits: typing.Optional[typing.Sequence[ScriptEditSchema]] = OMIT,
        archived: typing.Optional[bool] = OMIT,
        trigger_enabled: typing.Optional[bool] = OMIT,
        trigger_category: typing.Optional[JobTriggerCategory] = OMIT,
        trigger_instrument_id: typing.Optional[str] = OMIT,
        trigger_conditions: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        parameter_definitions: typing.Optional[typing.Sequence[ParameterDefinitionSchema]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolsJobSchema:
        """
        Change a job's name, description, code, trigger, or parameters, or
        archive it.

        Only the fields passed are changed. To change part of the script, pass
        edits: exact replacements of text in the current script. Pass code only to
        replace the whole script. New code is stored as a new version of the job's
        script, so earlier executions keep the version they ran. To create a job,
        use create_job instead.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        job_id : str

        name : typing.Optional[str]
            New name for the job.

        description : typing.Optional[str]
            New description for the job. Pass an empty string to clear it.

        code : typing.Optional[str]
            Complete new Python source for the job's script, stored as a new script version. Declare dependencies inline in a PEP 723 `# /// script` block. For a change to part of the script, pass edits instead.

        edits : typing.Optional[typing.Sequence[ScriptEditSchema]]
            Replacements applied in order to the job's current script, stored as a new script version. Each old_string is matched against the script as left by the edits before it. If any edit fails to match, no change is saved. Cannot be combined with code.

        archived : typing.Optional[bool]
            True archives the job, hiding it from the active job list; false restores it.

        trigger_enabled : typing.Optional[bool]
            True creates or replaces the job's trigger from the trigger fields; false removes it.

        trigger_category : typing.Optional[JobTriggerCategory]
            What runs the job automatically: file_uploaded runs it on each uploaded file that matches the conditions; job_completed runs it on the output files of another job's executions; schedule configures a recurring cron schedule. Required when trigger_enabled is true.

        trigger_instrument_id : typing.Optional[str]
            Restricts a file_uploaded trigger to files from this instrument.

        trigger_conditions : typing.Optional[typing.Dict[str, typing.Any]]
            Filters on the triggering event. For file_uploaded, any of file_name_pattern, file_extensions (list of strings starting with '.'; files with no extension always pass), source_type, min_size_kb, and max_size_kb (both inclusive). file_name_pattern is a case-sensitive glob in which * matches any characters, including folder separators, ? matches one character, and '/' and '\\' each match either separator. It must match the file's whole path or the part after any separator, so '*.csv' and 'run_*.csv' match files in any folder. For job_completed, source_job_id (required) and statuses (list drawn from completed and failed; defaults to completed). For schedule, cron (required five-field expression: minute, hour, day of month, month, day of week) and timezone (required IANA timezone, e.g. America/Los_Angeles). Cron supports numbers, month and weekday names, *, ranges, lists, and steps.

        parameter_definitions : typing.Optional[typing.Sequence[ParameterDefinitionSchema]]
            Inputs the script reads at run time. Each is rendered as a form control when the job is run on the platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolsJobSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.update(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            job_id,
            name=name,
            description=description,
            code=code,
            edits=edits,
            archived=archived,
            trigger_enabled=trigger_enabled,
            trigger_category=trigger_category,
            trigger_instrument_id=trigger_instrument_id,
            trigger_conditions=trigger_conditions,
            parameter_definitions=parameter_definitions,
            request_options=request_options,
        )
        return _response.data

    async def start(
        self,
        *,
        request: typing.Optional[StartJobExecutionSchema] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Open a job execution for a script running outside the platform.

        Pass the returned job_execution_id to the write and upload-file tools so
        everything one script run produces is attributed to a single execution and
        can be inspected or reverted as a unit. Pass job_id to run under an
        existing job, job_name to run under a job of that name (created if
        missing), or neither to run under the default off-platform job.

        The execution is marked running immediately. Close it as completed or
        failed when the script finishes. Pass timeout_minutes to have the platform
        fail it after that long if the script has not closed it, so a crashed
        script does not leave it running forever.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        request : typing.Optional[StartJobExecutionSchema]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric, StartJobExecutionSchema

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.start(
                request=StartJobExecutionSchema(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start(request=request, request_options=request_options)
        return _response.data

    async def close(
        self,
        execution_id: str,
        *,
        status: UpdateJobExecutionStatusSchemaStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffPlatformJobExecutionSchema:
        """
        Close a job execution as completed or failed.

        Call this when an off-platform script finishes. Either status is final:
        re-sending the same status is a no-op, and changing it is rejected. Only
        executions opened by the start tool are accepted; the platform records
        every other execution's status itself.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        status : UpdateJobExecutionStatusSchemaStatus
            How the run ended. Either status is final: the execution cannot change status afterwards.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffPlatformJobExecutionSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.close(
                execution_id="execution_id",
                status="completed",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.close(execution_id, status=status, request_options=request_options)
        return _response.data

    async def revert(
        self, execution_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RevertResultSchema:
        """
        Revert a job execution by deleting the rows it created.

        Deletes the execution's created objects and their linked raw rows in one
        transaction, for undoing a test write that failed validation. Updates and
        deletes cannot be reversed and are reported as warnings in the result.

        Requires an API key with the `write` scope.

        Parameters
        ----------
        execution_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RevertResultSchema
            OK

        Examples
        --------
        import asyncio

        from labric import AsyncLabric

        client = AsyncLabric(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.jobs.revert(
                execution_id="execution_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revert(execution_id, request_options=request_options)
        return _response.data
